version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjs_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network-dev

  redis:
    image: redis:7-alpine
    container_name: redis_db_dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass 12345
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - app-network-dev

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_dev
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data_dev:/db
    networks:
      - app-network-dev

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  redisinsight_data_dev:
    driver: local

networks:
  app-network-dev:
    driver: bridge
